# backend/notification.py

import os
import httpx
from dotenv import load_dotenv

load_dotenv()

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")


def send_doctor_report_slack(
    doctor_name: str,
    date: str,
    total_appointments: int,
    patients: list
):
    """Send doctor's appointment summary report to Slack"""

    # Build patient list text
    if patients:
        patient_lines = "\n".join([
            f"• {p['name']} at {p['time']} — {p['reason']} ({p['status']})"
            for p in patients
        ])
    else:
        patient_lines = "No appointments scheduled."

    # Build Slack message blocks (nicely formatted)
    message = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📋 Appointment Report — {doctor_name}"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Date:*\n{date}"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Total Appointments:*\n{total_appointments}"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Patient Details:*\n{patient_lines}"
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by Doctor Assistant 🤖"
                    }
                ]
            }
        ]
    }

    try:
        response = httpx.post(SLACK_WEBHOOK_URL, json=message)
        if response.status_code == 200:
            print(f"[Slack] Report sent successfully for {doctor_name}")
            return {"success": True, "message": "Report sent to Slack"}
        else:
            print(f"[Slack] Failed — Status: {response.status_code}")
            return {"success": False, "error": response.text}
    except Exception as e:
        print(f"[Slack] Error: {e}")
        return {"success": False, "error": str(e)}